name: Build Test Cases

on:
  push:
    branches:
      - mainv4  # Set a branch to deploy
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # ,windows-latest, macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.104.2'
          extended: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install pagefind --global
      - name: Build Website
        run: hugo --minify
      - run: npx pagefind --source public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/mainv4'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch : gh-pages-v4
          publish_dir: ./public
